### ISSUE TITLE
D3.11.3.2.C: Include photometric likelihood in cross-match probability

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#13]
Once the Astrometric Uncertainty Functions (AUFs) include systematic perturbation components in deriving the probability of match between two potential counterparts given their separation (#12), the probability density functions (PDFs) may suffer large, non-Gaussian tails, which would dramatically increase the number of potential counterparts for sources across two catalogues, removing the advantages gained by considering probability-based cross-matches (#11) in the first place.

To overcome this again, we can turn to the additional piece of information in a photometric catalogue: the photometry. In a general, statistical sense, essentially all stars of 15th magnitude in one catalogue will have, somewhere near them, stars of, say, 18th magnitude in a different filter in another catalogue. Thus, if we take the brightness distribution of all sources within some radius of these 15th magnitude sources and subtract from it the overall distribution of sources not near to these sources (i.e., calculate a _background_ distribution of objects, assuming this "field" distribution is independent of position), we -- in theory -- are left with the distribution of brightnesses of objects in the opposing catalogue that correspond to objects of 15th magnitude in the first catalogue. Repeating this for all subsets of objects, we can build up a magnitude-magnitude relationship between objects across the two catalogues. Once we've also created the distribution of sources nowhere near _any_ object in the opposing catalogue -- "orphan" stars, sometimes called the "field" distribution, as a holdover from stellar cluster syntax -- we can compare source matches on photometric grounds.

Analogous to the astrometric aspect, we can compare the probability of two potential counterparts as being two detections of one object or two sets of detections of two separate sources by considering their likelihood of being drawn from this correlated "counterpart" distribution, or of being separately drawn from the two independent sets of "field star" distributions. These two likelihoods can simply by multiplied by their corresponding astrometric likelihoods to obtain the likelihood of the two sources being counterparts, or not being counterparts, on _both_ astrometric _and_ photometric grounds.

This would then very easily reject any "interloper" counterpart considerations picked up by the increase in effective match radius from the non-Gaussian AUF, as the 15th magnitude source in catalogue A might consider two objects in catalogue B as having similar _astrometric_ likelihoods, but if one of them is 18th magnitude and very likely based on the _ensemble_ correlation between objects in the two catalogues having 15th magnitude and 18th magnitude objects overlay each other in space respectively, while the other object is 22nd magnitude and not correlated in the ensemble, then the photometric information heavily favours one source instead of the other.

With this, and the completion of "task 3" of the phase B proposal, the flexible cross-match algorithm as detailed by Wilson & Naylor (2018a, 2018b) is fully implemented.

**Comment by tms-epcc** [comment]
Tom will close this.
