### ISSUE TITLE
T3.11.4.4: Documentation for codebase

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#15]
As part of a more formal code development structure -- and to enable continuation of this project into the start of LSST operation -- the code must be documented. This likely has three parts:

 - Individual functions and classes must have robust docstrings, clearly laying out the API for each individual aspect of the code
- Larger scale APIs should be detailed, with high-level overview, interconnectivity diagrams, etc., and expectations of data input and output structures.
- Some more basic "getting started" level introduction material, detailing how to install the package, create appropriate inputs (catalogues and metadata files, most likely), and perhaps interpret key outputs, such as making likelihood ratio plots or understanding photometric contamination.

It also encompasses a more general, non-code specific documentation of aspects of the catalogue creation process such as the methodology behind generating the "parameters" of a chosen catalogue (such as its AUF weighting, PSF information, galaxy count model, etc.) in the case of a new dataset being included in the LSST matching set.

**Comment by tms-epcc** [comment]
In [April'22 to Sept'22 plan](https://lsst-uk.atlassian.net/wiki/download/attachments/766574618/six_month_plan_apr_22_sept_22.pdf?version=3&modificationDate=1648644533673&cacheVersion=1&api=v2), 2nd batch of documentation is expected by early Aug'22, 3rd batch by early Sept'22

**Comment by tms-epcc** [comment]
24/AUG/22

**Comment by tms-epcc** [comment]
13/OCT/22
- drafting outline of the documentation contents

**Comment by tms-epcc** [comment]
03/NOV/22
- close to be finished. 
- when ready will be available with at existing Macauf documentation at https://onoddil.github.io/macauff/
