### ISSUE TITLE
T3.11.4.0: Run initial test of full scale, fully-implemented cross-match

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#16]
Subject to progress on #6 this goal is to set up the DAC hardware supported, API implemented cross-match code on the DAC in full operation mode, once it has been established it meets any runtime requirements (#7).

This test of the cross-matching algorithm and infrastructure forms the first part of a "science verification" series of goals: a _Gaia_-_WISE_ cross-match across the entire sky, to verify our crowding algorithms, and a full catalogue merging is possible across all Galactic and extra-galactic sightlines.

**Comment by tms-epcc** [comment]
In April'22 to Sept'22 plan, this is expected by mid-July'22.

**Comment by tms-epcc** [comment]
27/JUL/22
-this is blocked by #18

**Comment by tms-epcc** [comment]
13/OCT/22
- @Onoddil will discuss with @MikeeRead how to do this test
- this will take place on CSD3

**Comment by tms-epcc** [comment]
03/NOV/22
- code merged, CSV done
- next need @Onoddil and @MikeeRead to take this forward

**Comment by tms-epcc** [comment]
01/DEC/22
- minor code changes implemented
- following D S-M's testing, last item is to add to the code  a check for remote server hanging
- @MikeeRead has made the skinny tables and will run these through the partitioner, put on CSD3, once code ready,  @Onoddil will run the test.

**Comment by tms-epcc** [comment]
20/DEC/22
- implemented D S-M fix for remote server 
- CAT-WISE pre-processing steps were not all-sky ready so now calling this within the D S-M code instead.  Implementation ongoing.  
- Once ready, need to generate the files and save on CSD3 and run the test

**Comment by tms-epcc** [comment]
@Onoddil 
- the further necessary (as above) fix is implemented
- CAT-WISE pre-processing steps were not all-sky ready so now calling this within the D S-M code instead. Implementation of this ongoing.
- Once ready, need to generate the files and save on CSD3 and run the test.

**Comment by Onoddil** [comment]
Following discussion yesterday, this tracker has been split into two separate items: the first (this item #16) now tracking the measureable output of the deliverable D3.11.4 with #57 tracking the milestone completion item for MS016.

As above, these may be combined but are likely to be two separately completed items now, and hence need updating separately from now on.

**Comment by tms-epcc** [comment]
02/FEB/23
- @Onoddil ran with the existing DR3.  This ran successfully from a code perspective.
- Science validation still to happen but this needs newly uploaded DR3.
- MS016 will have a brief explanation (or similar) as evidence milestone is passed and so will also who this initial test passed
