### ISSUE TITLE
T3.11.4.6.D: Create test suite of tools for catalogue parameterisation

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#18]
This deliverable is to formalise and extend the code spread over the numerous tests performed -- in this work package or otherwise -- to "parameterise" a photometric catalogue. To perform a robust match including the effects of contaminant sources we require things such as the information surrounding its TRILEGAL simulations, information on its extragalactic population (and reddening etc. in its passbands), PSF details for its passbands, and -- with the extensions to the algorithms from #1 -- information on how to transition between "high" signal-to-noise regimes and "low" SNRs for the background-dominated algorithm implementation.

Thus it would be useful to create a standardised test suite where these pieces of information can be obtained and verified by evaluation with e.g. _Gaia_ cross-matches and AUF overplotting. This would involve the creation of a smaller, companion package of functions.

**Comment by tms-epcc** [comment]
- expecting to make main cross-match code based on the outputs from existing test code.
- this will the allow #16 to be tackled
- then will return to this

**Comment by tms-epcc** [comment]
08/JUN/22
- prototype code fits for all parameters for sky for test case.
- now need to move this into the main code base and deal with testing of this

**Comment by tms-epcc** [comment]
29/JUN/22
- still progressing, almost finished

**Comment by tms-epcc** [comment]
27/JUL/22
- waiting on a merge of the code-base with @dsloanm-epcc 
- after merge will move in to review with @Tim-Naylor

**Comment by tms-epcc** [comment]
10/AUG/22
- changing order i.e. will review first with Tim and then do the code merge

**Comment by tms-epcc** [comment]
24/AUG/22
- review (not line-by-line) took place comprising questions about the code, its purpose etc
