### ISSUE TITLE
T3.11.4.6.B: Create all-sky parameterisation of AUF transition

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#19]
As part of #1 we developed a model to improve the accuracy of the description of the perturbations due to blended objects, with two models in the extremes of high signal-to-noise ratio and background-dominated sources. We then describe a linear weighting between these models, which requires finalising in its functionality, making sufficiently generic to apply to the entire sky (in crowded, lower SNR regions like the Galactic center as well as much clearer extra-Galactic regions), and applicable to a wide range of catalogues.

**Comment by tms-epcc** [comment]
For timescales see https://lsst-uk.atlassian.net/wiki/download/attachments/766574618/six_month_plan_apr_22_sept_22.pdf?version=2&modificationDate=1647353978928&cacheVersion=1&api=v2

**Comment by tms-epcc** [comment]
13/APR/22
- tom still expecting to meet timescales

**Comment by tms-epcc** [comment]
27/APR/22
- Need to check and scale astrometric uncertainties in latest WISE. This needs to be tested.
- Note that the implementation of this code was not included in the original plan
- Due date for this task will be updated in March'22 quarterly update

**Comment by tms-epcc** [comment]
18/MAY/22
- Works all sky for one catalogue
- assuming works for all catalogues
