### ISSUE TITLE
D3.11.2.1: Code for example working catalogue cross-match

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#2]
The main bulk of the WP3.11 project is to write code to flexibly handle catalogue cross-matches which include the effects of source blending on the astrometry, and fold in photometric information of the objects to reject false matches.

In the current plan this would be specific to a single example catalogue, likely _Gaia_ and another catalogue, currently assumed to be _WISE_ to improve upon and supplement [Wilson & Naylor (2018)](https://ui.adsabs.harvard.edu/abs/2018MNRAS.481.2148W/abstract) as the most obvious and well-understood test case.

This goal is included mostly for completeness and comparison with the original proposal timeline; it is mostly being skipped over in the actual workflow, and is mostly merged with #6. The corresponding deliverable for D3.11.2 will likely be replaced with the outcomes of #11, an interim goal of the work corresponding to deliverable D3.11.3, with a roughly similar expected delivery date (D3.11.2 is due 30/Nov/20 -- really the end of October for review purposes -- while #11 is due roughly to coincide with the UKDAC1 delivery, slated for 1/Oct/20).

**Comment by tms-epcc** [comment]
Note that #11 D3.11.3.2.A is now be used for the deliverable D3.11.2

**Comment by Onoddil** [comment]
Further to the above comment, the revised deliverable for D3.11.2 should be #8 now as per the Oct20-Mar21 six month plan.
