### ISSUE TITLE
D3.11.2 - Demonstration of DAC Integration of Preliminary Software

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#20]

**Comment by tms-epcc** [comment]
Agreed at 25/NOV/2020 that change request be submitted to delay deliverable due date

**Comment by tms-epcc** [comment]
Change Request C019 (see [Change Register](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/751108134/Change+Register+Phase+B)) submitted to 03/DEC/2020 Exec Group for approval.

**Comment by tms-epcc** [comment]
End date moved to 31st Jan 2021 in light of approval of change request C018 [(see change register)](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/751108134/Change+Register+Phase+B) at the 03/DEC/20 Exec Group meeting

**Comment by tms-epcc** [comment]
Deliverable submitted for review 07/JAN/21. See [review tracking ticket](https://app.zenhub.com/workspaces/lsstuk-project-mgmnt-5ee3ae947fc4e92804a2c64a/issues/lsst-uk/management-dac-dev-wp1.3/23) for status of the review.

**Comment by tms-epcc** [comment]
At [05/MAR/21 WP3.11 planning process meeting](https://api.media.atlassian.com/file/9ca7e402-abcf-48f7-bd36-44bed13fdcb7/binary?token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzNDMyZmNkYy1kZTM1LTRmMDktOGNjYy04NTI3NWQyMmJjYWEiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjljYTdlNDAyLWFiY2YtNDhmNy1iZDM2LTQ0YmVkMTNmZGNiNyI6WyJyZWFkIl19LCJleHAiOjE2MTU2MjM4MjgsIm5iZiI6MTYxNTU0MDg0OH0.vk7AWUw1MDj6h-xE5naxEuHeZ5_L98_ntssTmh5tT_Y&client=3432fcdc-de35-4f09-8ccc-85275d22bcaa&name=LUSC-WP3.11-Planning-2021-03-04.txt) it was agreed to change the dissemination level of the deliverable from "Restricted to project" to "Public"
Deliverable approved by Exec Group 05/MAR/12
