### ISSUE TITLE
D3.11.3 - Demonstration of full DAC integrable software

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#21]
[Change Request C022]( https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C022-Rebaselining_WP3.11.pdf?api=v2) resulted in deliverable title changing.

**Comment by tms-epcc** [comment]
Change Request C019 (see [Change Register](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/751108134/Change+Register+Phase+B)) submitted to 03/DEC/2020 Exec Group for approval.

**Comment by tms-epcc** [comment]
End date moved to 30th April 2021 in light of approval of change request C018 [(see change register)](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/751108134/Change+Register+Phase+B) at the 03/DEC/20 Exec Group meeting
