### ISSUE TITLE
T3.11.4.5: Optimisation and scalability testing of code

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#7]
Ensure that runtimes and core/memory usage of any DAC-run cross-match code are within reasonable ranges, and perform optimisation to reduce requirements if found to be outside of acceptable limits. Necessitates the creation of "wrapper" code to split larger catalogues into small sky regions, pad with 'halos' to avoid splitting islands where possible, and combine match combinations in a new final stage, handling halo duplications.

**Comment by tms-epcc** [comment]
See https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/766574618/WP3.11+Cross+matching+and+astrometry+at+LSST+depths?preview=/766574618/2859466771/scaling_relations_wp3.11.pdf

**Comment by tms-epcc** [comment]
See https://github.com/lsst-uk/Science-Support-WP2.5/issues/25 for DSM kanban

**Comment by tms-epcc** [comment]
27/JUL/22
- had hoped to do some optimisations other than the parallelisation but thus far it is unclear whether these will provide any benefit.  Will continue to investigate further.  Note this is not critical.

**Comment by tms-epcc** [comment]
10/AUG/22
- optimisations were actually worthwhile.
- after the code merge with @dsloanm-epcc, will add these.

**Comment by tms-epcc** [comment]
24/AUG/22
- #18 finished
- now need to determine the order of the code merges with @dsloanm-epcc 
- final step to complete is the data merge, currently considering whether or not to parallelise this too

**Comment by tms-epcc** [comment]
13/OCT/22
- code merges done
- data merges is now part of the parallelisation
- @dsloanm-epcc optimisation work is close to finishing.

**Comment by tms-epcc** [comment]
03/NOV/22
- @Onoddil no longer believes need to test with double the density of sources
