### ISSUE TITLE
MS016.1: Deploy code on DAC

### ISSUE THREAD

**Issue by Onoddil** [lsst-uk/Cross-Match-WP3.11#8]
As part of scaling up to full DAC operations, the _Gaia_-_WISE_ all-sky cross-matches should be run, to complete a full end-to-end run of the matches on DAC hardware and ingestion of end results into the user-facing software.

**Comment by tms-epcc** [comment]
@markgbeckett @Onoddil @Tim-Naylor agreed what constitutes the DAC and so this has been done.
